### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by stephenandekian** [kontent-ai/model-generator-js#33]
### Brief bug description

What went wrong?
When using the code generated Model process it appears that API is trying to fetch a model that was removed earlier in the day. 

`Created './content-types/bio.ts'
Created './content-types/image__video_cover.ts'
Created './content-types/icon_block_item.ts'
Failed with error:
Error: Could not find content type with id 'bdc395af-d19c-473c-b8c1-094a74e69b34'`

### Repro steps

1. Create a few content types in kontent.ai. 
2. Generate those models (content types) or consume them with API
3. Remove one of the content types.
4. See if it trys to still pull in the deleted content type by its id. 

### Expected behavior

Should not build deleted models. 

### Additional context

Full Error:

`Failed with error:
Error: Could not find content type with id 'bdc395af-d19c-473c-b8c1-094a74e69b34'
    at C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-mappers.js:29:19
    at C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:471:43
    at Array.map (<anonymous>)
    at DeliveryContentTypeGenerator.extractLinkedItemsAllowedTypes (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:471:31)
    at DeliveryContentTypeGenerator.getLinkedItemsAllowedTypes (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:445:35)
    at DeliveryContentTypeGenerator.mapElementType (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:378:53)
    at DeliveryContentTypeGenerator.getExtendedElements (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:425:40)
    at DeliveryContentTypeGenerator.getContentTypeImports (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:111:39)
    at DeliveryContentTypeGenerator.getModelCode (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:170:35)
    at DeliveryContentTypeGenerator.createContentTypeModel (C:\source\repos\corp-web-www-venafi\node_modules\@kontent-ai\model-generator\dist\cjs\lib\generators\delivery\delivery-content-type.generator.js:244:27)`

Add links to screenshots, if possible.

**Comment by stephenandekian** [comment]
Appears it was not cache but an old model tied to a LinkedItem in another Model.
